# Generated by Django 5.1.5 on 2025-02-02 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='associated_thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatapi.chatthread'),
            preserve_default=False,
        ),
    ]
