# Generated by Django 5.1.5 on 2025-02-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_message_associated_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='role',
        ),
    ]
